In [3]:
import tables_io
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("/global/homes/s/sajkov/umap_nz_cal.mplstyle")

In [4]:
directory_bigLePhareDataset = "/pscratch/sd/s/sajkov/analysis_pipeline/runs/07Jul26"
date_bigLePhareDataset = directory_bigLePhareDataset.split("/")[-1]
directory_smallLePhareDataset = "/pscratch/sd/s/sajkov/analysis_pipeline/runs/smallLePhareSet_07Jul26"
date_smallLePhareDataset = directory_smallLePhareDataset.split("/")[-1]

In [7]:
PHOTOMETRY_DeepField_small         = tables_io.read(f"{directory_smallLePhareDataset}/PHOTOMETRY_DeepField_noisy_{date_smallLePhareDataset}.pq")
PHOTOMETRY_DeepField_lePhare_small = tables_io.read(f"{directory_smallLePhareDataset}/PHOTOMETRY_DeepField_noisy_lpReference_{date_smallLePhareDataset}.pq")
PHOTOMETRY_WideFastDeep_small      = tables_io.read(f"{directory_smallLePhareDataset}/PHOTOMETRY_WideFastDeep_noisy_{date_smallLePhareDataset}.pq")

TRUEREDSHIFTS_DeepField_small             = np.load(f"{directory_smallLePhareDataset}/TRUEREDSHIFTS_DeepField.npy")
TRUEREDSHIFTS_DeepField_lpReference_small = np.load(f"{directory_smallLePhareDataset}/TRUEREDSHIFTS_DeepField_lpReference.npy")
TRUEREDSHIFTS_WideFastDeep_small          = np.load(f"{directory_smallLePhareDataset}/TRUEREDSHIFTS_WideFastDeep.npy")

column_list None
column_list None
column_list None

In [8]:
PHOTOMETRY_DeepField_big         = tables_io.read(f"{directory_bigLePhareDataset}/PHOTOMETRY_DeepField_noisy_{date_bigLePhareDataset}.pq")
PHOTOMETRY_DeepField_lePhare_big = tables_io.read(f"{directory_bigLePhareDataset}/PHOTOMETRY_DeepField_noisy_lpReference_{date_bigLePhareDataset}.pq")
PHOTOMETRY_WideFastDeep_big      = tables_io.read(f"{directory_bigLePhareDataset}/PHOTOMETRY_WideFastDeep_noisy_{date_bigLePhareDataset}.pq")

TRUEREDSHIFTS_DeepField_big             = np.load(f"{directory_bigLePhareDataset}/TRUEREDSHIFTS_DeepField.npy")
TRUEREDSHIFTS_DeepField_lpReference_big = np.load(f"{directory_bigLePhareDataset}/TRUEREDSHIFTS_DeepField_lpReference.npy")
TRUEREDSHIFTS_WideFastDeep_big          = np.load(f"{directory_bigLePhareDataset}/TRUEREDSHIFTS_WideFastDeep.npy")

column_list None
column_list None
column_list None

In [27]:
PHOTOZS_DeepField_lePhare_big = tables_io.read(f"{directory_bigLePhareDataset}/PHOTOZS_DeepField_lePhare_{date_bigLePhareDataset}.pq")["photo-z"]
PHOTOZS_flexZBoost_photoZs_big = np.load(f"{directory_bigLePhareDataset}/PHOTOZS_flexZBoost_photoZs.npy")
PHOTOZS_flexZBoost_specZs_big = np.load(f"{directory_bigLePhareDataset}/PHOTOZS_flexZBoost_specZs.npy")

PHOTOZS_DeepField_lePhare_small = tables_io.read(f"{directory_smallLePhareDataset}/PHOTOZS_DeepField_lePhare_{date_smallLePhareDataset}.pq")["photo-z"]
PHOTOZS_flexZBoost_photoZs_small = np.load(f"{directory_smallLePhareDataset}/PHOTOZS_flexZBoost_photoZs.npy")
PHOTOZS_flexZBoost_specZs_small = np.load(f"{directory_smallLePhareDataset}/PHOTOZS_flexZBoost_specZs.npy")

column_list None
column_list None

In [15]:
print(np.mean(TRUEREDSHIFTS_DeepField_big - TRUEREDSHIFTS_DeepField_small))
print(np.mean(TRUEREDSHIFTS_WideFastDeep_big - TRUEREDSHIFTS_WideFastDeep_small))

0.0
0.0

In [ ]:
print(np.nanmean(PHOTOMETRY_DeepField_small - PHOTOMETRY_DeepField_big))
print(np.nanmean(PHOTOMETRY_DeepField_lePhare_small - PHOTOMETRY_DeepField_lePhare_big))
print(np.nanmean(PHOTOMETRY_WideFastDeep_small - PHOTOMETRY_WideFastDeep_big))

0.0
0.0
0.0

In [43]:
np.mean(PHOTOZS_DeepField_lePhare_big - PHOTOZS_DeepField_lePhare_small)

np.float64(5.1833537462187e-19)

In [42]:
np.min(PHOTOZS_flexZBoost_photoZs_small - PHOTOZS_flexZBoost_photoZs_big)

np.float64(0.0)

In [29]:
TRUEREDSHIFTS_DeepField_small

array([0.9499769 , 5.2313423 , 0.02873397, ..., 1.3036196 , 2.9985065 ,
       2.8448644 ], shape=(10000,), dtype=float32)

In [21]:
PHOTOMETRY_DeepField_lePhare_small - PHOTOMETRY_DeepField_lePhare_big

,LSST_u,LSST_u_err,LSST_g,LSST_g_err,LSST_r,LSST_r_err,LSST_i,LSST_i_err,LSST_z,LSST_z_err,...,HSC_MB_11,HSC_MB_11_err,HSC_MB_12,HSC_MB_12_err,HSC_MB_13,HSC_MB_13_err,HSC_MB_14,HSC_MB_14_err,HSC_MB_15,HSC_MB_15_err
index,,,,,,,,,,,,,,,,,,,,,
153,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
357,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
534,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1247,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1998815,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1998972,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1998980,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1999090,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
PHOTOMETRY_DeepField_lePhare_small

,LSST_u,LSST_u_err,LSST_g,LSST_g_err,LSST_r,LSST_r_err,LSST_i,LSST_i_err,LSST_z,LSST_z_err,...,HSC_MB_11,HSC_MB_11_err,HSC_MB_12,HSC_MB_12_err,HSC_MB_13,HSC_MB_13_err,HSC_MB_14,HSC_MB_14_err,HSC_MB_15,HSC_MB_15_err
index,,,,,,,,,,,,,,,,,,,,,
136251,25.755294,0.034701,25.722531,0.014878,25.610362,0.011741,25.461142,0.009954,25.251973,0.014398,...,25.548880,0.202867,25.756715,0.229516,25.476507,0.205890,24.948767,0.166959,25.585022,0.377638
1259537,28.666202,0.417841,27.884637,0.098898,27.148917,0.043489,26.029918,0.015339,25.489128,0.017505,...,26.013405,0.297391,25.822520,0.242361,25.703935,0.248717,25.345541,0.233127,24.444529,0.147550
1083960,25.758995,0.034815,25.234566,0.010259,25.280860,0.009307,25.263554,0.008749,25.236545,0.014221,...,25.216123,0.152920,25.373525,0.166214,25.559820,0.220738,25.168528,0.201110,25.330886,0.308956
460895,24.968174,0.017491,24.157074,0.006005,23.018181,0.005095,22.486287,0.005031,22.312584,0.005081,...,22.550226,0.014851,22.444601,0.013014,22.343704,0.013526,22.235410,0.015535,21.926814,0.016208
1460280,27.297324,0.135683,26.122270,0.020807,25.753570,0.013105,25.626695,0.011199,25.428825,0.016644,...,25.659254,0.222480,25.692086,0.217499,25.354355,0.185758,25.471129,0.258545,25.754123,0.430098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990415,25.430463,0.026044,25.165522,0.009782,24.963833,0.007708,24.557139,0.006249,25.169957,0.013486,...,23.744573,0.041804,25.119887,0.133652,25.005622,0.137846,25.416562,0.247212,25.648404,0.396642
1375716,27.328424,0.139379,26.738642,0.035745,25.852315,0.014172,25.484627,0.010117,25.354952,0.015657,...,25.268262,0.159908,25.613299,0.203621,25.527346,0.214839,24.842674,0.152467,24.928792,0.222394
729621,27.234965,0.128549,27.271512,0.057463,26.999375,0.038066,26.654542,0.026138,26.426892,0.039710,...,26.453055,0.420035,inf,inf,26.479344,0.458713,25.985101,0.389565,26.374336,0.674097
1049791,23.957302,0.008306,23.936448,0.005689,23.807200,0.005394,23.443686,0.005178,23.268978,0.005455,...,23.220412,0.026273,23.311838,0.027008,23.304269,0.030623,23.128780,0.033594,23.223142,0.050346
536600,26.634516,0.075889,26.662756,0.033415,26.658985,0.028152,26.516116,0.023160,26.428695,0.039774,...,26.079523,0.313600,inf,inf,26.866220,0.608094,26.480811,0.564139,25.964996,0.503669

In [22]:
PHOTOMETRY_DeepField_lePhare_big

,LSST_u,LSST_u_err,LSST_g,LSST_g_err,LSST_r,LSST_r_err,LSST_i,LSST_i_err,LSST_z,LSST_z_err,...,HSC_MB_11,HSC_MB_11_err,HSC_MB_12,HSC_MB_12_err,HSC_MB_13,HSC_MB_13_err,HSC_MB_14,HSC_MB_14_err,HSC_MB_15,HSC_MB_15_err
index,,,,,,,,,,,,,,,,,,,,,
136251,25.755294,0.034701,25.722531,0.014878,25.610362,0.011741,25.461142,0.009954,25.251973,0.014398,...,25.548880,0.202867,25.756715,0.229516,25.476507,0.205890,24.948767,0.166959,25.585022,0.377638
1259537,28.666202,0.417841,27.884637,0.098898,27.148917,0.043489,26.029918,0.015339,25.489128,0.017505,...,26.013405,0.297391,25.822520,0.242361,25.703935,0.248717,25.345541,0.233127,24.444529,0.147550
1083960,25.758995,0.034815,25.234566,0.010259,25.280860,0.009307,25.263554,0.008749,25.236545,0.014221,...,25.216123,0.152920,25.373525,0.166214,25.559820,0.220738,25.168528,0.201110,25.330886,0.308956
460895,24.968174,0.017491,24.157074,0.006005,23.018181,0.005095,22.486287,0.005031,22.312584,0.005081,...,22.550226,0.014851,22.444601,0.013014,22.343704,0.013526,22.235410,0.015535,21.926814,0.016208
1460280,27.297324,0.135683,26.122270,0.020807,25.753570,0.013105,25.626695,0.011199,25.428825,0.016644,...,25.659254,0.222480,25.692086,0.217499,25.354355,0.185758,25.471129,0.258545,25.754123,0.430098
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1072520,25.495780,0.027583,25.300377,0.010749,24.876486,0.007369,24.394398,0.005951,23.858496,0.006252,...,24.459052,0.078942,24.026806,0.050963,23.943955,0.054106,23.762766,0.059085,23.768847,0.081770
1173921,25.990368,0.042776,25.803931,0.015904,25.319457,0.009548,25.030435,0.007653,25.258719,0.014477,...,24.491141,0.081215,25.431023,0.174557,25.126890,0.153020,25.372894,0.238464,25.987651,0.512132
1091973,25.841296,0.037458,24.867817,0.008118,24.728988,0.006880,24.665501,0.006493,24.608726,0.009000,...,24.599356,0.089358,24.751289,0.096890,24.630785,0.099434,24.688345,0.133473,24.537156,0.159756
1895711,24.942536,0.017119,23.760546,0.005507,22.433836,0.005033,21.253877,0.005003,20.591613,0.005003,...,21.108651,0.006232,20.876420,0.005752,20.625268,0.005631,20.434421,0.005736,20.330903,0.006138
727224,24.448293,0.011549,24.272068,0.006219,24.183300,0.005760,24.004367,0.005485,23.916135,0.006377,...,23.910779,0.048480,23.894401,0.045289,23.872147,0.050752,23.809051,0.061570,23.861242,0.088721